name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: make image
        run: make image
      - name: make image
        run: cd deploy/spdk
      - name: Build the root Docker image
        run: docker build --tag spdkdev:$(date +%s) .
